# SPDX-FileCopyrightText: 2022 - 2023 Robin Vobruba <hoijui.quaero@gmail.com>
#
# SPDX-License-Identifier: Unlicense

[package]
name = "osh-dir-std"
version = "0.8.0"
license = "AGPL-3.0-or-later"
authors = ["Robin Vobruba <hoijui.quaero@gmail.com>"]
description = """
Helps humans and machines deal with the
*OSH directory standard*:
<https://github.com/hoijui/osh-dir-std>
"""
repository = "https://github.com/hoijui/osh-dir-std-rs"
homepage = "https://github.com/hoijui/osh-dir-std-rs"
keywords = ["norm", "osh", "directory", "structure"]
categories = ["command-line-utilities", "filesystem", "text-processing"]
readme = "../README.md"
edition = "2021"

[lints]
workspace = true

[dependencies]
anyhow = "1.0"
osh_dir_std = { version = "0.8.0", path = "../lib" }
clap = { version = "4.0", features = ["std", "cargo", "help"], default-features = false }
cli_utils = { version = "0.7", package = "cli_utils_hoijui" }
const_format = "0.2"
log = "0.4"
once_cell = "1.16"
regex = "1.7"
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
tracing = { version = "0.1", default-features = false }
tracing-subscriber = { version = "0.3" }
